# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true

# Proxy configuration for Gradle dependencies
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=5780
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=5780
systemProp.http.nonProxyHosts=localhost|127.0.0.1|*.aliyuncs.com|*.aliyun.com
systemProp.https.nonProxyHosts=localhost|127.0.0.1|*.aliyuncs.com|*.aliyun.com
